title: Martha's Munches
description: Martha's Munches - a blog about awesome food and

url: https://martha.ellis.scot
baseurl: ""
paginate_path: "page:num/"
permalink: :title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about/

social:
   github:
   twitter:
   facebook:
   email:

google_analytics: "UA-1089638-18"
